### ISSUE TITLE
Similarity to ember-truth-helpers

### ISSUE THREAD

**Issue by buschtoens** [robert-allan-frank/ember-logic-fns#1]
Just saw your addon in the current issue of Ember Weekly.

Did you know that there's already [`ember-truth-helpers`](https://github.com/jmurphyau/ember-truth-helpers), which is the status quo community standard for performing logic in the template?

It also offers all of the helpers, that your addon has. 🙂

**Comment by robert-allan-frank** [comment]
Awesome ... thanks for passing on the info ... I'll check it out!!!
